export const operazioniAutenticazione = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  MODIFICA_PROFILO: 'MODIFICA_PROFILO',
}

export const operazioniPersone = {
  INSERISCI_CLIENTE: 'INSERISCI_CLIENTE',
  VISUALIZZA_CLIENTI: 'VISUALIZZA_CLIENTI',
  OTTIENI_TUTTI_I_CLIENTI: 'OTTIENI_TUTTI_I_CLIENTI',
  ELIMINA_CLIENTI: 'ELIMINA_CLIENTI',
  MODIFICA_CLIENTI: 'MODIFICA_CLIENTI',
};

export const operazioniServizi = {
  INSERISCI_SERVIZIO: 'INSERISCI_SERVIZIO',
  VISUALIZZA_SERVIZI: 'VISUALIZZA_SERVIZI',
  OTTIENI_TUTTI_I_SERVIZI: 'OTTIENI_TUTTI_I_SERVIZI',
  ELIMINA_SERVIZI: 'ELIMINA_SERVIZI',
  MODIFICA_SERVIZI: 'MODIFICA_SERVIZI'
}

export const operazioniLavori = {
  INSERISCI_LAVORO: 'INSERISCI_LAVORO',
  VISUALIZZA_LAVORI: 'VISUALIZZA_LAVORI',
  ELIMINA_LAVORI: 'ELIMINA_LAVORI',
  ELIMINA_LAVORI_RANGE_GIORNI: 'ELIMINA_LAVORI_RANGE_GIORNI',
  MODIFICA_LAVORI: 'MODIFICA_LAVORI',
}









