export const operazioniAutenticazione = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  MODIFICA_PROFILO: 'MODIFICA_PROFILO',
}

export const operazioniPersone = {
  INSERISCI_CLIENTE: 'INSERISCI_CLIENTE',
  VISUALIZZA_CLIENTI: 'VISUALIZZA_CLIENTI',
  OTTIENI_TUTTI_I_CLIENTI: 'OTTIENI_TUTTI_I_CLIENTI',
  ELIMINA_CLIENTI: 'ELIMINA_CLIENTI',
  MODIFICA_CLIENTI: 'MODIFICA_CLIENTI',
};

export const operazioniProfessionisti = {
  INSERISCI_PROFESSIONISTA: 'INSERISCI_PROFESSIONISTA',
  VISUALIZZA_PROFESSIONISTI: 'VISUALIZZA_PROFESSIONISTI',
  OTTIENI_TUTTI_I_PROFESSIONISTI: 'OTTIENI_TUTTI_I_PROFESSIONISTI',
  ELIMINA_PROFESSIONISTI: 'ELIMINA_PROFESSIONISTI',
  MODIFICA_PROFESSIONISTI: 'MODIFICA_PROFESSIONISTI'
}

export const operazioniLavori = {
  INSERISCI_LAVORO: 'INSERISCI_LAVORO',
  VISUALIZZA_LAVORI_CLIENTI: 'VISUALIZZA_LAVORI_CLIENTI',
  VISUALIZZA_LAVORI_PROFESSIONISTI: 'VISUALIZZA_LAVORI_PROFESSIONISTI',
  ELIMINA_LAVORI: 'ELIMINA_LAVORI',
  ELIMINA_LAVORI_RANGE_GIORNI: 'ELIMINA_LAVORI_RANGE_GIORNI',
  MODIFICA_LAVORI: 'MODIFICA_LAVORI',
}









