export default {
  // Azioni autenticazione
  LOGIN: "LOGIN", 
  MODIFICA_PROFILO: "MODIFICA_PROFILO", 

  // Azioni clienti
  HANDLE_INSERT_CLIENTE: "HANDLE_INSERT_CLIENTE", 
  HANDLE_SEARCH_CLIENTI: "HANDLE_SEARCH_CLIENTI", 
  HANDLE_EDIT_CLIENTI: "HANDLE_EDIT_CLIENTI", 
  HANDLE_DELETE_CLIENTI: "HANDLE_DELETE_CLIENTI",
  
  // Azioni servizi:
  HANDLE_INSERT_SERVIZIO: "HANDLE_INSERT_SERVIZIO", 
  HANDLE_SEARCH_SERIZI: "HANDLE_SEARCH_SERIZI", 
  HANDLE_EDIT_SERVIZI: "HANDLE_EDIT_SERVIZI", 
  HANDLE_DELETE_SERVIZI: "HANDLE_DELETE_SERVIZI",  

  // Azioni lavori
  HANDLE_INSERT_LAVORO: "HANDLE_INSERT_LAVORO", 
  HANDLE_SEARCH_LAVORI: "HANDLE_SEARCH_LAVORI", 
  HANDLE_SEARCH_LAVORI_RANGE_FILE: "HANDLE_SEARCH_LAVORI_RANGE_FILE", 
  HANDLE_SEARCH_ENTRATE_LAVORI: "HANDLE_SEARCH_ENTRATE_LAVORI", 
  HANDLE_EDIT_LAVORI: "HANDLE_EDIT_LAVORI", 
  HANDLE_DELETE_LAVORI: "HANDLE_DELETE_LAVORI", 
  HANDLE_DELETE_LAVORI_RANGE_FILE: "HANDLE_DELETE_LAVORI_RANGE_FILE", 

  // Azioni spese
  HANDLE_INSERT_SPESA: "HANDLE_INSERT_SPESA", 
  HANDLE_SEARCH_SPESE: "HANDLE_SEARCH_SPESE", 
  HANDLE_SEARCH_SPESE_RANGE_FILE: "HANDLE_SEARCH_SPESE_RANGE_FILE", 
  HANDLE_SEARCH_USCITE_SPESE: "HANDLE_SEARCH_USCITE_SPESE", 
  HANDLE_EDIT_SPESE: "HANDLE_EDIT_SPESE", 
  HANDLE_DELETE_SPESE: "HANDLE_DELETE_SPESE", 
  HANDLE_DELETE_SPESE_RANGE_FILE: "HANDLE_DELETE_SPESE_RANGE_FILE", 
};









